logging:
  level:
     org:
       springframework:
         security: DEBUG

spring:
   data:
      mongodb.host: localhost
      mongodb.port: 12345
      mongodb.uri: mongodb://localhost/test
      mongo.repositories.enabled: true