# While in development mode, you can configure the config server to pick up configuration files from
# the file system e.g. uri: file://Users/xxx/sample-config
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/reefminder/reefminder-config

# Defines the port where the config server is running so that rest of the services can pick up 
# their external configurations
server:
  port: 8888          